INTERVIEW_QUESTION_PROMPT = (
    "You are an AI-powered interview question generator.\n\n"
    "Role: {job_role}\n"
    "Experience Level: {experience_level}\n"
    "{job_description_section}\n\n"
    "Your task:\n"
    "- Generate exactly 5 interview questions and their ideal answers.\n"
    "- Format strictly as:\n"
    "Q1: <Question 1>\n"
    "A1: <Answer 1>\n"
    "Q2: <Question 2>\n"
    "A2: <Answer 2>\n"
    "Q3: <Question 3>\n"
    "A3: <Answer 3>\n"
    "Q4: <Question 4>\n"
    "A4: <Answer 4>\n"
    "Q5: <Question 5>\n"
    "A5: <Answer 5>\n\n"
    "Important:\n"
    "- Do not include any introductions, summaries, or extra explanations.\n"
    "- Only output the questions and answers exactly in the specified format."
)
